#!/bin/bash

#Created by Shoeb Rehman
#This script counts the bytes of each given argument and displays the sum of all arguments that are greater than 100000.

let sum=0
for file_name in $@
do
        if [ -r "$file_name" ]
        then
                file_size=$(wc -c "$file_name" | cut -d ' ' -f1)
                echo "$file_name: $file_size"
                if [ $file_size -gt 100000 ]
                then
                        let sum+="$file_size"
                fi
        fi
done
if [ $sum -gt 100000 ]
then
        echo "$sum"
fi
